### ISSUE TITLE
Add ssh to netshoot

### ISSUE THREAD

**Issue by dustingrant** [nicolaka/netshoot#103]
Would be nice to add an SSH client to the package list

**Comment by amodaugustin** [comment]
+1

**Comment by BurlyLuo** [comment]
docker pull burlyluo/nettoolbox
you can use this image which based on alpine linux.

**Comment by nicolaka** [comment]
fixed with 4a728d215b05142c0dce5e3abd5f746ebca70d49

**Comment by jonashartwig** [comment]
thanks
