### ISSUE TITLE
Push image to an additional registry like GHCR

### ISSUE THREAD

**Issue by onedr0p** [nicolaka/netshoot#104]
**Is your feature request related to a problem? Please describe.**

Dockerhub rate limits

**Describe the solution you'd like**

Push netshoot to an additional registry like Quay or GHCR

**Comment by nicolaka** [comment]
Done with 9c48d587556b7a2241b710f65a6ef26601a62983

**Comment by onedr0p** [comment]
I think you need to go into the package settings and make it public. 

https://github.com/nicolaka?tab=packages&repo_name=netshoot

Thanks!

**Comment by nicolaka** [comment]
Switched it to public.

**Comment by onedr0p** [comment]
It looks like I'm still not seeing it.

**Comment by nicolaka** [comment]
can you check if you can download it though ? 

![image](https://user-images.githubusercontent.com/11139046/169073823-b098d54c-d8b7-485a-a676-037bfeae64ae.png)

**Comment by onedr0p** [comment]
I can pull it, but I think you need to link it to your repo to show up in the packages section on your repo landing page.

```
✖ docker pull ghcr.io/nicolaka/netshoot:latest
latest: Pulling from nicolaka/netshoot
df9b9388f04a: Already exists
77ad91f73bcf: Pull complete
93006b97b1aa: Pull complete
d5c83131d384: Pull complete
d1b85b893323: Pull complete
f843ef8b30ce: Pull complete
4f4fb700ef54: Pull complete
6df125936a60: Pull complete
aa7ac85e7566: Pull complete
6ca113f241c3: Pull complete
272e97d419e8: Pull complete
89b5480bc2a1: Pull complete
352df3b9a11b: Pull complete
ea9b226b0d8b: Pull complete
Digest: sha256:1116ede25c69cd4e3effa2dfbdc35e6638c8faceabd4fbbd334dfbb108c07095
Status: Downloaded newer image for ghcr.io/nicolaka/netshoot:latest
ghcr.io/nicolaka/netshoot:latest
```
