### ISSUE TITLE
Dockerfile: alphabetize list of packages

### ISSUE THREAD

**Issue by trapier** [nicolaka/netshoot#11]
it's good form to sort packages installed alphabetically to make it easier to read the list, especially when the list is as long as the one here.  please make it so with the next change (addition or removal) on the list.

**Comment by nicolaka** [comment]
@trapier can you think of a programmatic way to do that?

**Comment by trapier** [comment]
define programmatic.  using vim i would:

1. `V` line-highlight all packages
2. `:!sort` to sort
3. fixup line-endings if needed (not, in this case, because `vim` is still alphabetically last).

**Comment by nicolaka** [comment]
Closed with https://github.com/nicolaka/netshoot/pull/12

**Comment by trapier** [comment]
Thanks @timelf123!

**Comment by timelf123** [comment]
np, in sublime select lines and hit `f9`!
