### ISSUE TITLE
Netshoot kubectl plugin

### ISSUE THREAD

**Issue by nilic** [nicolaka/netshoot#127]
Hi, I am a big fan of netshoot and so I've developed a `kubectl` plugin which can spin up netshoot quickly without having to memorize the correct syntax for `kubectl run` or `kubectl debug`:

https://github.com/nilic/kubectl-netshoot

Main goal was to cover all the example use cases from [Netshoot with Kubernetes](https://github.com/nicolaka/netshoot#netshoot-with-kubernetes). I have also added a few additional example use cases to the readme (debugging nodes, running command instead of attaching to an interactive shell).

Through flags, plugin allows for selecting which netshoot container image to use, as well as whether to run the container in the host network's namespace.

If this sounds useful, please consider adding a link to my project to netshoot readme. I am also open to any suggestions or ideas how to further improve the plugin. Thanks 🙂

**Comment by nilic** [comment]
@nicolaka

**Comment by nicolaka** [comment]
@nilic this is awesome! I thought of easier ways to integrate netshoot with kubectl and having a plugin definitely helps. Thank you! I will spend some time playing with the plugin and update the README to point to it 👍🏽

**Comment by nicolaka** [comment]
Thank you again! I added a reference to your plugin in the readme in #131 !
