### ISSUE TITLE
Can you please not set the `HOSTNAME` environment variable in the Dockerfile?

### ISSUE THREAD

**Issue by avbenavides** [nicolaka/netshoot#167]
This is a request.
Can you please not set the `HOSTNAME` environment variable in the Dockerfile?
A non-written convention in the K8s and Docker world is that the `HOSTNAME` environment variable value is the container or host ID. The netshoot Dockerfile breaks this convention by setting the `HOSTNAME` variable to "netshoot".
The uniqueness of `HOSTNAME` is used (that I've seen) for:

- Identifying the container in logs
- Uniqueness in metrics
- Other scripting that requires uniqueness that survives reboots/restarts (i.e. depending on the life-cycle, the container may be restarted in case of crash/fail exit code).

**Comment by nicolaka** [comment]
Hello, You can specify --hostname flag to docker run or k8s pod spec to set the hostname for the container at runtime.

**Comment by avbenavides** [comment]
True but I'm using netshoot to run load tests and that means more than one pod, and thus it is important that the hostname matches the pod name.
