### ISSUE TITLE
error symbol not found when executing command 'host' or 'dig'

### ISSUE THREAD

**Issue by lcaille** [nicolaka/netshoot#25]
Hi,

Since the PR #24, when executing dig or host, I have this error

> Error relocating /usr/lib/libisc.so.1200: explicit_bzero: symbol not found.

**Comment by nicolaka** [comment]
@lcaille please try nicolaka/netshoot:edge , it's using the alpine:edge which addresses the isssue.

**Comment by lcaille** [comment]
It works with the edge version, thank you!
