### ISSUE TITLE
Add termshark for inspecting packets?

### ISSUE THREAD

**Issue by John-Lin** [nicolaka/netshoot#34]
`termshark` is a terminal user-interface for tshark. https://github.com/gcla/termshark

The UI is much like Wireshark easy to inspect large pcap files or sniff live interfaces however tshark has to be added as run-time dependency. This will increase docker image size from 195M to 311M, I was wondering if you could add `termshark` into netshoot image? or any thoughts

I could help doing this PR

**Comment by nicolaka** [comment]
feel free to submit a PR @John-Lin :)

**Comment by nicolaka** [comment]
I added it @John-Lin . However, can you help me with documenting exact steps to launch termshark? it seems that  there needs to be specific linux capabilitites added when launching the pod/container to be able to run it. Can you please document that in the readme and provide some examples there?

**Comment by John-Lin** [comment]
Sure. I believe that give the linux capabilities with NET_ADMIN and CAP_NET_RAW should work. I'll add docs later.

**Comment by John-Lin** [comment]
See #48 @nicolaka
