### ISSUE TITLE
feature request: include https://httpie.org/

### ISSUE THREAD

**Issue by frisi** [nicolaka/netshoot#47]
hi there

thanks for maintaining this useful product!

i'd love to see https://httpie.org/ being included in netshoot.

compared to curl/wget it is much easier/intuitive to invoke http requests (esp. when dealing with json) 

please let me know what you do think about including it.

thanks in advance!

**Comment by wmcnamee-tunein** [comment]
yes please

**Comment by nicolaka** [comment]
done.
