### ISSUE TITLE
Why is the input in the terminal buggy?

### ISSUE THREAD

**Issue by SinGlEBW** [nicolaka/netshoot#59]
The input in the terminal does not work properly. It shows incorrectly, but if I expand the terminal a little, the error will visually disappear, but the input continues to give this effect. When deleting, the terminal also behaves strangely. 
Introduced the "dig mysql"
![Снимок14](https://user-images.githubusercontent.com/55041499/108828664-2dfeef80-75d8-11eb-990f-fa08b438b33b.JPG)
expanded the terminal
![Снимок66](https://user-images.githubusercontent.com/55041499/108828598-17589880-75d8-11eb-8e2f-c5d7e95c8470.JPG)
removed 2 characters from the end
![Снимок444](https://user-images.githubusercontent.com/55041499/108828758-4ff87200-75d8-11eb-8c46-c35b9f3f89ad.JPG)
removed all characters
![Снимо63к](https://user-images.githubusercontent.com/55041499/108828820-61da1500-75d8-11eb-99df-b0f68b1f3b28.JPG)

**Comment by Dishock** [comment]
> The input in the terminal does not work properly. It shows incorrectly, but if I expand the terminal a little, the error will visually disappear, but the input continues to give this effect. When deleting, the terminal also behaves strangely.
> Introduced the "dig mysql"

Did you find a fix? This happens in my system too...

**Comment by nicolaka** [comment]
@SinGlEBW I'm gonna look into it. Probabaly will switch the profile as I did have some buggy behaviour in the past as well. stay tuned.

**Comment by AaronViviano** [comment]
Noting that this also happens on my system with VS Code:

Version: 1.54.3 (system setup)
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T10:55:45.459Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by nicolaka** [comment]
@AaronViviano @SinGlEBW I pushed a new version and switched to zsh with cleaner term profile. let me know if you're seeing same issue.

**Comment by AaronViviano** [comment]
@nicolaka I am not seeing the same issue any more. Though the rendering of the terminal in VS code is still odd.
![image](https://user-images.githubusercontent.com/5307593/112764954-7000c400-8fd0-11eb-80e0-b3d76071e11c.png)

I'm also seeing a yellow alpha numeric string of 12 characters before command prompt line. Not sure what they are there for. Looks like a shortened git hash. While I highly doubt this is the case, I'm not including it in the picture in case this is some sort of security related key.

**Comment by nicolaka** [comment]
@AaronViviano the hash is just the container name that turns into the hostname. The new zsh profile uses the hostname in the prompt that's all.

**Comment by AaronViviano** [comment]
@nicolaka Good to know! Thank you.
