### ISSUE TITLE
nslookup throws "nslookup: can't resolve '(null)': Name does not resolve"

### ISSUE THREAD

**Issue by quadespresso** [nicolaka/netshoot#6]
Running from a freshly spawned container:

```
/ # nslookup www.google.com
nslookup: can't resolve '(null)': Name does not resolve

Name:      www.google.com
Address 1: 172.217.9.4 dfw28s02-in-f4.1e100.net
Address 2: 2607:f8b0:4000:811::2004 dfw28s01-in-x04.1e100.net
/ #
```

I did some digging online, and found a couple references to this:

1. [[RESOLVED] Service name resolution broken on alpine and docker 1.11.1-cs1](https://forums.docker.com/t/resolved-service-name-resolution-broken-on-alpine-and-docker-1-11-1-cs1/19307)
1. [virtualbox-host-dns-resolver with alpine linux](https://github.com/docker/machine/issues/3451)

For the second reference listed above, scroll to the bottom. It appears that the issue might be with how Alpine Linux (at least when run as a container) [may be mishandling AAAA records](https://bugs.alpinelinux.org/issues/6221).

It's not yet apparent how best to deal with the `can't resolve '(null)': Name does not resolve` issue, short of putting a wrapper script around it to filter out the noise.

**Comment by nicolaka** [comment]
can I close this one @quadespresso ?

**Comment by quadespresso** [comment]
SGTM
