### ISSUE TITLE
permission denied on OpenShift 4.x

### ISSUE THREAD

**Issue by webner** [nicolaka/netshoot#65]
OpenShift fails to create to container with following error message:

Error: container create failed: time="2021-04-12T15:03:47Z" level=error msg="container_linux.go:366: starting container process caused: chdir to cwd (\"/root\") set in config.json failed: permission denied"

**Comment by jbalasko** [comment]
in OpenShift the containers are not allowed to run with ROOT user, so the runtime user is not allowed to change into `/root` directory. `WORKDIR` is set in netshoot Dockerfile on [line 75](https://github.com/nicolaka/netshoot/blob/0349eb1293dd1af3160cdb5bae197db506b4f431/Dockerfile#L75)
To resolve the issue, override it in your YaML manifest using `workingDir` container's field, see [here](https://stackoverflow.com/questions/36634614/how-to-set-the-workdir-of-a-container-launched-by-kubernetes)
