### ISSUE TITLE
Include docker-compose example in the documentation

### ISSUE THREAD

**Issue by oschlueter** [nicolaka/netshoot#79]
Hey,

it took me a while to figure out how to achieve this so I figured others might benefit from my work. Here's an example of a docker-compose.yml capturing all network traffic of an nginx container:

    version: "3.6"
    services:
      tcpdump:
        image: nicolaka/netshoot
        depends_on:
          - nginx
        command: tcpdump -i eth0 -w /data/nginx.pcap
        network_mode: service:nginx
        volumes:
          - $PWD/data:/data
    
      nginx:
        image: nginx:alpine
        ports:
          - 80:80

Would you like to include this in the documentation?

**Comment by righel** [comment]
+1
thanks @oschlueter I was exactly looking for this.

**Comment by nicolaka** [comment]
@oschlueter feel free to open a PR against the README page to include this docker-compose example.
