### ISSUE TITLE
Add semantic versioning on tags

### ISSUE THREAD

**Issue by Ornias1993** [nicolaka/netshoot#81]
Currently tags are pushed to dockerhub with some digest/hash instead of decent semantic versions.
Please fix this so people could automatic versioning tools like renovate with this container.

**Comment by nicolaka** [comment]
good idea. I'll adopt some sort of versioning moving forward.

**Comment by Ornias1993** [comment]
Also, a bit out-of-scope, but while you're add it... maybe also start uploading the container to github registry as well? To paypass those pesky dockerhub ratelimits :)

**Comment by nicolaka** [comment]
fixed with https://github.com/nicolaka/netshoot/pull/86

**Comment by Ornias1993** [comment]
awesome. thanks! :)
