### ISSUE TITLE
 error in multiple command

### ISSUE THREAD

**Issue by houshym** [nicolaka/netshoot#87]
on a k3s cluster( containerd runtime), I use 
kubectl debug   mypod  -n myns  -it --image=nicolaka/netshoot --share-processes --copy-to=mypod-debug
then I tried to run different commands but some of them has errors:
1- termshark error 

bash-5.1# termshark
Termshark is initializing - please wait...
(The termshark UI will start when packets are detected on DisplayPort AUX channel monitor capture...)
Cannot capture on device DisplayPort AUX channel monitor capture: exit status 1 (exit code 1)
See https://termshark.io/no-root for more info.
bash-5.1#

2- ctop 

ctop - error ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
  │                                                                                                                                                                                      │
  │  [04:55:39 UTC] Get "http://unix.sock/info": dial unix /var/run/docker.sock: connect: no such file or directory                                                                      │
  │                                                                                                                                                                                      │
  │  [04:55:39 UTC] attempting to reconnect...

**Comment by nicolaka** [comment]
@houshym for 1. you need to add NET_ADMIN and NET_RAW caps when launching the pod (see https://github.com/nicolaka/netshoot#termshark).  For 2, ctop expects to connect to the docker socket on /var/run/docker.sock so you need to mount it within netshoot container.
