### ISSUE TITLE
Can't open pcap file

### ISSUE THREAD

**Issue by MoonyBou** [nicolaka/netshoot#91]
I ran this command to generate a tcpdump cap file

docker run -it --rm --net container:<container-name> nicolaka/netshoot tcpdump -s 0 -i wlp2s0 -w - > tcpdump.pcap

But Wireshark can't open that file, nor any other online analyzer I tried

**Comment by MoonyBou** [comment]
Someone? :p

**Comment by swfchn** [comment]
tcpdump on the bash of nicolaka/netshoot and then transfer the pcap file to pc.

**Comment by swfchn** [comment]
docker run -it -rm -net container: <your container> nicolaka/netshoot 
once you got the command line input
tcpdump -s 0 -w /var/log/tcpdump.pcap
use vscode/docker to transfer the file

**Comment by MoonyBou** [comment]
Yaaaay!!! It works perfectly, thank you very very much @swfchn !! :D
For the record: I used _docker cp_ to transfer the file to the host
