### ISSUE TITLE
Build new Docker Image

### ISSUE THREAD

**Issue by GaLaXy102** [nicolaka/netshoot#93]
Hello,
thank you for your work with netshoot, it is a great help to me.

Today I wanted to iperf a SDN, but sadly 5f2b4a6 (iperf3) is not yet included in the Docker image.

Would you mind rebuilding and reuploading the image to Docker Hub?

Thanks in advance!

**Comment by nicolaka** [comment]
@GaLaXy102 thanks for the feedback . I'm working on pushing new images to DockerHub and releasing tag v0.2.

**Comment by nicolaka** [comment]
Done. I released a new version v0.2 pointing to latest.
